export const QUESTION_TEXT = "Will you be my Valentine?";
export const YES_TEXT = "Yes! 💖";
export const NO_TEXT = "No 💔";
export const CELEBRATION_CAPTION = "I can't believe you said yes!!! 😍";
export const COUPLE_PHOTO_PATH = "/couple-photo.jpeg";
export const MOBILE_WARNING = "You need to open this on a computer!";
export const VOLUME_HINT = "Turn up your volume! 🔊";
export const CELEBRATION_SONG_PATH = "/celebration-song.mp3";
export const MOBILE_BREAKPOINT = 768;
